/**
 * @created 13.04.16
 *
 * @author Popov Nikolay <cejixo3dr@gmail.com>
 * @copyright Beeplans 2016
 */
angular.module('FSUAClientApplication', [
        'ngRoute',
        'ui.bootstrap',
        'btford.socket-io',
        'CacheTemplatesAutoGeneratedApplication'
    ])


    .config(function ($routeProvider) {
        /*$routeProvider
         .when('/', {
         templateUrl: 'life_watch_view',
         controller: 'LifeWatchViewController',
         controllerAs: 'LifeWatchView'
         })
         .when('/main', {
         templateUrl: 'main_view',
         controller: 'MainViewController',
         controllerAs: 'MainView'
         })
         .when('/git/post-commit', {
         templateUrl: 'git_post_commit_view',
         controller: 'GitPostCommitBaseController',
         controllerAs: 'GitPostCommitBase'
         })
         .when('/dashboard', {
         templateUrl: 'dashboard_view',
         controller: 'DashboardBaseController',
         controllerAs: 'DashboardBase'
         })
         .otherwise({
         redirectTo: '/'
         });*/
    })
;