/**
 * @created 13.04.16
 *
 * @author Popov Nikolay <cejixo3dr@gmail.com>
 * @copyright Beeplans 2016
 */
angular.module('FSUAClient.application', [
        'ngRoute',
        'ngAnimate',
        'ui.bootstrap',
        'btford.socket-io',
        'CacheTemplatesAutoGenerated.application',
        'FSUAClient.dashboard.application'
    ])


    .config(function ($routeProvider) {
        $routeProvider
            .when('/', {
                templateUrl: 'dashboard_list',
                controller: 'FSUAClient.dashboard.list.controller',
                controllerAs: 'FSUAClientDashboardListController'
            })
            .otherwise({
                redirectTo: '/'
            })
        ;


        /*$routeProvider
         .when('/', {
         templateUrl: 'life_watch_view',
         controller: 'LifeWatchViewController',
         controllerAs: 'LifeWatchView'
         })
         .when('/main', {
         templateUrl: 'main_view',
         controller: 'MainViewController',
         controllerAs: 'MainView'
         })
         .when('/git/post-commit', {
         templateUrl: 'git_post_commit_view',
         controller: 'GitPostCommitBaseController',
         controllerAs: 'GitPostCommitBase'
         })
         .when('/dashboard', {
         templateUrl: 'dashboard_view',
         controller: 'DashboardBaseController',
         controllerAs: 'DashboardBase'
         })
         .otherwise({
         redirectTo: '/'
         });*/
    })
;